INSERT INTO products (name, stock, price) VALUES ('Smartphone', 50, 699.99);
INSERT INTO products (name, stock, price) VALUES ('Laptop', 30, 1299.99);
INSERT INTO products (name, stock, price) VALUES ('Tablet', 40, 499.99);
INSERT INTO products (name, stock, price) VALUES ('Smartwatch', 70, 199.99);
INSERT INTO products (name, stock, price) VALUES ('Wireless Headphones', 100, 149.99);
INSERT INTO products (name, stock, price) VALUES ('Bluetooth Speaker', 80, 89.99);
INSERT INTO products (name, stock, price) VALUES ('Smart TV', 25, 799.99);
INSERT INTO products (name, stock, price) VALUES ('Gaming Console', 45, 399.99);
INSERT INTO products (name, stock, price) VALUES ('External Hard Drive', 60, 129.99);
INSERT INTO products (name, stock, price) VALUES ('Digital Camera', 35, 599.99);
INSERT INTO products (name, stock, price) VALUES ('Wireless Mouse', 90, 29.99);
INSERT INTO products (name, stock, price) VALUES ('Keyboard', 85, 49.99);
INSERT INTO products (name, stock, price) VALUES ('Monitor', 50, 299.99);
INSERT INTO products (name, stock, price) VALUES ('Printer', 40, 199.99);
INSERT INTO products (name, stock, price) VALUES ('Router', 70, 89.99);
INSERT INTO products (name, stock, price) VALUES ('Smart Home Hub', 65, 149.99);
INSERT INTO products (name, stock, price) VALUES ('VR Headset', 20, 399.99);
INSERT INTO products (name, stock, price) VALUES ('Fitness Tracker', 75, 99.99);
INSERT INTO products (name, stock, price) VALUES ('Drone', 30, 999.99);
INSERT INTO products (name, stock, price) VALUES ('Portable Charger', 100, 39.99);
